"""
Unit tests for security.py — verifies PyJWT + direct bcrypt implementation.
TDD RED phase: these tests must fail until security.py is rewritten.
"""
import pytest
from src.core.security import hash_password, verify_password, create_access_token, decode_token


def test_hash_password_returns_bcrypt_prefix():
    """hash_password must return a str starting with $2b$12$"""
    h = hash_password("testpassword")
    assert isinstance(h, str), "hash_password must return str"
    assert h.startswith("$2b$12$"), f"Expected $2b$12$ prefix, got: {h[:10]}"


def test_verify_password_correct():
    """verify_password returns True for correct plaintext against its own hash."""
    h = hash_password("testpassword")
    assert verify_password("testpassword", h) is True


def test_verify_password_wrong():
    """verify_password returns False for wrong plaintext."""
    h = hash_password("testpassword")
    assert verify_password("wrongpassword", h) is False


def test_verify_password_passlib_compat():
    """verify_password works against an existing passlib-generated hash ($2b$ prefix is identical)."""
    # Hash produced by passlib's CryptContext(schemes=["bcrypt"]) for "Secret1234"
    passlib_hash = "$2b$12$Rt3Hkrs4QJ.tnR35WluM4uFabwXCcZqXPV7bGQLdkYvgcW9wdEmem"
    # Generated by: CryptContext(schemes=["bcrypt"]).hash("Secret1234") — $2b$ prefix, rounds=12
    assert verify_password("Secret1234", passlib_hash) is True
    assert verify_password("wrongpassword", passlib_hash) is False


def test_create_access_token_returns_non_empty_str():
    """create_access_token returns a non-empty string (valid JWT)."""
    tok = create_access_token("user-123")
    assert isinstance(tok, str)
    assert len(tok) > 0


def test_decode_token_roundtrip():
    """decode_token(create_access_token(sub)) returns dict with sub == original subject."""
    tok = create_access_token("user-123")
    payload = decode_token(tok)
    assert isinstance(payload, dict)
    assert payload["sub"] == "user-123"


def test_decode_token_garbage_raises_value_error():
    """decode_token raises ValueError('Invalid token') for garbage input."""
    with pytest.raises(ValueError, match="Invalid token"):
        decode_token("garbage.not.a.jwt")


def test_security_uses_pyjwt():
    """Verify that security.py imports jwt (PyJWT) directly, not jose."""
    import src.core.security as sec_module
    import inspect
    source = inspect.getsource(sec_module)
    assert "import jwt" in source, "security.py must use 'import jwt' (PyJWT)"
    assert "passlib" not in source, "security.py must not import passlib"
    assert "jose" not in source, "security.py must not import jose"


def test_security_uses_bcrypt():
    """Verify that security.py imports bcrypt directly."""
    import src.core.security as sec_module
    import inspect
    source = inspect.getsource(sec_module)
    assert "import bcrypt" in source, "security.py must use 'import bcrypt'"
