"""modify users table

Revision ID: d4347a4be06c
Revises: f5d1fc213b5b
Create Date: 2025-12-31 11:49:38.344874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4347a4be06c'
down_revision: Union[str, Sequence[str], None] = 'f5d1fc213b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with a temporary server_default so existing rows get a value
    op.add_column(
        'users',
        sa.Column('name', sa.String(), server_default='User', nullable=False)
    )
    # Drop the default so future inserts rely on application-side defaults/validation
    op.alter_column('users', 'name', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
