"""add caching indexes

Revision ID: f5d1fc213b5b
Revises: 177ff3515823
Create Date: 2025-12-29 23:56:21.689279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d1fc213b5b'
down_revision: Union[str, Sequence[str], None] = '177ff3515823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payments_user', 'subscription_payments', ['user_id'], unique=False)
    op.create_index('ix_payments_user_paid_at', 'subscription_payments', ['user_id', 'paid_at'], unique=False)
    op.create_index('ix_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_user_category', 'subscriptions', ['user_id', 'category_id'], unique=False)
    op.create_index('ix_subscriptions_user_next_renewal', 'subscriptions', ['user_id', 'next_renewal_date'], unique=False)
    op.create_index('ix_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_user_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_next_renewal', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_category', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user', table_name='subscriptions')
    op.drop_index('ix_payments_user_paid_at', table_name='subscription_payments')
    op.drop_index('ix_payments_user', table_name='subscription_payments')
    # ### end Alembic commands ###
